name: Deploy to Synology NAS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          password: ${{ secrets.NAS_PASSWORD }}
          script: |
            echo '${{ secrets.NAS_PASSWORD }}' | sudo -S sh -c "cd /docker/rfm && git config --global --add safe.directory /docker/rfm && git fetch origin master && git reset --hard origin/master && /usr/local/bin/docker-compose -f /docker/rfm/docker-compose.yml up -d --build --force-recreate backend frontend"